// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyConsoleApp.Data;

#nullable disable

namespace database_seeder.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241024211858_NullableColumns")]
    partial class NullableColumns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MyConsoleApp.Models.Krupierzy", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nazwisko")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("Pesel")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("PoczatekPracy")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("Krupierzy");
                });

            modelBuilder.Entity("MyConsoleApp.Models.Lokalizacje", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<short>("Kolumna")
                        .HasColumnType("smallint");

                    b.Property<short>("Pietro")
                        .HasColumnType("smallint");

                    b.Property<short>("Rzad")
                        .HasColumnType("smallint");

                    b.HasKey("ID");

                    b.ToTable("Lokalizacje");
                });

            modelBuilder.Entity("MyConsoleApp.Models.Rozgrywki", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("DataKoniec")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataStart")
                        .HasColumnType("datetime2");

                    b.Property<int>("FK_KrupierID")
                        .HasColumnType("int");

                    b.Property<int>("FK_UstawienieStoluID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("FK_KrupierID");

                    b.HasIndex("FK_UstawienieStoluID");

                    b.ToTable("Rozgrywki");
                });

            modelBuilder.Entity("MyConsoleApp.Models.Stoly", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("FK_TypGryID")
                        .HasColumnType("int");

                    b.Property<short>("LiczbaMiejsc")
                        .HasColumnType("smallint");

                    b.Property<decimal?>("MaksymalnaStawka")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MinimalnaStawka")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID");

                    b.HasIndex("FK_TypGryID");

                    b.ToTable("Stoly");
                });

            modelBuilder.Entity("MyConsoleApp.Models.Transakcje", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("FK_RozgrywkaID")
                        .HasColumnType("int");

                    b.Property<int>("FK_TypTransakcjiID")
                        .HasColumnType("int");

                    b.Property<decimal>("Kwota")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID");

                    b.HasIndex("FK_RozgrywkaID");

                    b.HasIndex("FK_TypTransakcjiID");

                    b.ToTable("Transakcje");
                });

            modelBuilder.Entity("MyConsoleApp.Models.TypGry", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("NazwaGry")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.ToTable("TypGry");
                });

            modelBuilder.Entity("MyConsoleApp.Models.TypTransakcji", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Typ")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.ToTable("TypTransakcji");
                });

            modelBuilder.Entity("MyConsoleApp.Models.UstawienieStolu", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime?>("DataKoniec")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataStart")
                        .HasColumnType("datetime2");

                    b.Property<int>("FK_LokalizacjaID")
                        .HasColumnType("int");

                    b.Property<int>("FK_StolID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("FK_LokalizacjaID");

                    b.HasIndex("FK_StolID");

                    b.ToTable("UstawienieStolu");
                });

            modelBuilder.Entity("MyConsoleApp.Models.Rozgrywki", b =>
                {
                    b.HasOne("MyConsoleApp.Models.Krupierzy", "Krupierzy")
                        .WithMany()
                        .HasForeignKey("FK_KrupierID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyConsoleApp.Models.UstawienieStolu", "UstawienieStolu")
                        .WithMany()
                        .HasForeignKey("FK_UstawienieStoluID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Krupierzy");

                    b.Navigation("UstawienieStolu");
                });

            modelBuilder.Entity("MyConsoleApp.Models.Stoly", b =>
                {
                    b.HasOne("MyConsoleApp.Models.TypGry", "TypGry")
                        .WithMany()
                        .HasForeignKey("FK_TypGryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TypGry");
                });

            modelBuilder.Entity("MyConsoleApp.Models.Transakcje", b =>
                {
                    b.HasOne("MyConsoleApp.Models.Rozgrywki", "Rozgrywki")
                        .WithMany()
                        .HasForeignKey("FK_RozgrywkaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyConsoleApp.Models.TypTransakcji", "TypTransakcji")
                        .WithMany()
                        .HasForeignKey("FK_TypTransakcjiID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rozgrywki");

                    b.Navigation("TypTransakcji");
                });

            modelBuilder.Entity("MyConsoleApp.Models.UstawienieStolu", b =>
                {
                    b.HasOne("MyConsoleApp.Models.Lokalizacje", "Lokalizacje")
                        .WithMany()
                        .HasForeignKey("FK_LokalizacjaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyConsoleApp.Models.Stoly", "Stoly")
                        .WithMany()
                        .HasForeignKey("FK_StolID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lokalizacje");

                    b.Navigation("Stoly");
                });
#pragma warning restore 612, 618
        }
    }
}
